import test from 'node:test';import assert from 'node:assert/strict';
import {makeRoute,sampleRoute,CYCLE,mod,railCurve,BALL_R} from '../src/routes';import {Score,defaultScore,OFFSETS} from '../src/score';import {Transport} from '../src/transport';import {readState,encodeState,DEFAULT_CAMERA} from '../src/state';
test('transport rebases clocks without jumping, pauses and seeks negative time',()=>{let wall=10;const t=new Transport(()=>wall,5);wall+=3;assert.equal(t.read(),8);let audio=400;t.useClock(()=>audio);assert.equal(t.read(),8);audio++;assert.equal(t.read(),9);t.pause();audio+=99;assert.equal(t.read(),9);t.seek(-30);assert.equal(t.read(),-30);t.play();audio+=2;assert.equal(t.read(),-28);});
test('positive modular arithmetic handles negative and loop times',()=>{assert.equal(mod(-1,24),23);assert.equal(mod(24,24),0);assert.equal(mod(-48,24),0);});
test('each trajectory is continuous at every route boundary, including negative time',()=>{for(let i=0;i<8;i++){const r=makeRoute(i);for(const turn of [-3,0,4])for(const age of [-13.5,-7.5,-.3,0,.6,4.5,10.5]){const t=r.offset+age+CYCLE*turn;const a=sampleRoute(r,t-1e-5),b=sampleRoute(r,t+1e-5);assert.ok(a.position.distanceTo(b.position)<.002,`note ${i}, age ${age}: ${a.position.distanceTo(b.position)}`);}}});
test('trajectory sampling is deterministic and independent of order',()=>{for(let i=0;i<8;i++){const r=makeRoute(i);const expected=sampleRoute(r,19.2).position.toArray();for(const t of [20000,-99,15,400,.5])sampleRoute(r,t);assert.deepEqual(sampleRoute(r,19.2).position.toArray(),expected);assert.ok(sampleRoute(r,19.2).position.distanceTo(sampleRoute(r,19.2+24).position)<1e-8);}});
test('score scheduling partitions correctly without boundary duplicates',()=>{const s=new Score();const all=s.events(-.001,240);const chunks=[];for(let t=-.001;t<239.999;t+=.25)chunks.push(...s.events(t,Math.min(t+.25,240)));assert.equal(new Set(chunks.map(e=>e.id)).size,chunks.length);assert.deepEqual(chunks.map(e=>e.id),all.filter(e=>e.time<240).map(e=>e.id));assert.ok(all.every(e=>s.audible(e.note,e.time)));});
test('score edits preserve every in-flight event',()=>{const s=new Score();const before=s.events(7,20);const c=defaultScore();c.mask.fill(false);assert.equal(s.queue(c,4),6);assert.deepEqual(s.events(7,19.5).map(e=>e.id),before.filter(e=>e.time-13.5<6).map(e=>e.id));assert.ok(s.events(40,100).length===0);});
test('event lookup rejects unbounded requests',()=>{const s=new Score();assert.deepEqual(s.events(0,Infinity),[]);assert.deepEqual(s.events(-1e8,1e8),[]);});
test('shared state roundtrips with seed, mask and camera and bounds camera',()=>{const c=defaultScore();c.mask[2]=false;const encoded=encodeState(c,DEFAULT_CAMERA);assert.deepEqual(readState(encoded)?.s,c);const x=readState(encodeState(c,[300,-100,1e9]));assert.deepEqual(x?.c,[Math.PI,.30,17]);});
test('malformed and oversized shared state fails closed',()=>{for(const hash of ['%','{}','#s=%7B','a'.repeat(1000),encodeState({...defaultScore(),seed:-1},DEFAULT_CAMERA),encodeState({...defaultScore(),mask:[true]},DEFAULT_CAMERA),encodeState({...defaultScore(),variation:100},DEFAULT_CAMERA)])assert.equal(readState(hash),null);});

test('each marble clears every neighboring rail on the full descent',()=>{const routes=Array.from({length:8},(_,i)=>makeRoute(i));const rails=routes.map(r=>[-1,1].map(side=>railCurve(r.travel,side).getPoints(120)).flat());for(const r of routes)for(let k=0;k<=90;k++){const p=r.travel.getPointAt(k/90);for(let j=0;j<8;j++)if(j!==r.index)for(const q of rails[j])assert.ok(p.distanceTo(q)>BALL_R+.017,`route ${r.index} against ${j} at ${k}`);}});
test('lift pockets stay synchronized to the shared wheel at negative and positive times',()=>{for(let i=0;i<8;i++){const r=makeRoute(i);for(const t of [-120.3,-3.2,0,3,18,99]){const s=sampleRoute(r,t);if(s.stage!=='lift')continue;const angle=Math.atan2(s.position.y-2.38,s.position.x+1.65);const pocket=mod(angle+t*Math.PI/6,Math.PI/4);assert.ok(pocket<1e-8||Math.PI/4-pocket<1e-8);}}});
