import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {writeFile,mkdir} from 'node:fs/promises';
const target=process.argv[2]||'https://why-el.github.io/counterpoint/';const expected=process.argv[3];const run=process.argv[4]||'1';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
try{const context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:run==='1'?'reduce':'no-preference'});const page=await context.newPage();page.setDefaultTimeout(120000);const errors=[];const badResponses=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('response',r=>{if(r.status()>=400)badResponses.push({status:r.status(),url:r.url()});});
const response=await page.goto(target+'?test=1&release=1');assert.equal(response.status(),200);await page.waitForFunction(()=>!!window.__counterpoint);const canonical=page.url().split('?')[0];
const metadata=await page.evaluate(async()=>{const r=await fetch('./release.json',{cache:'no-store'});if(!r.ok)throw new Error('Release metadata '+r.status);return r.json();});if(expected)assert.equal(metadata.revision,expected);
let state=await page.evaluate(()=>window.__counterpoint.state());assert.equal(state.sound,false);assert.equal(state.playing,run!=='1');assert.equal(state.audioState,'not-created');
if(!state.playing)await page.locator('#play').click();await page.waitForTimeout(250);assert.equal((await page.evaluate(()=>window.__counterpoint.state())).playing,true);await page.locator('#play').click();
await page.locator('#time').focus();await page.keyboard.press('Home');assert.equal((await page.evaluate(()=>window.__counterpoint.state())).time,0);await page.keyboard.press('ArrowRight');assert.ok((await page.evaluate(()=>window.__counterpoint.state())).time>0);
await page.locator('#parts').click();await page.getByRole('button',{name:'D4 voice',exact:true}).click();assert.equal((await page.evaluate(()=>window.__counterpoint.state())).score.mask[2],false);await page.locator('#parts').click();
await page.locator('#sound').click();await page.waitForFunction(()=>window.__counterpoint.state().sound);assert.equal((await page.evaluate(()=>window.__counterpoint.state())).audioState,'running');await page.locator('#sound').click();
await page.locator('#scene').focus();await page.keyboard.press('ArrowRight');const saved=await page.evaluate(()=>window.__counterpoint.state());const share=await page.evaluate(()=>window.__counterpoint.share());await page.locator('#share').click();
await page.goto(share.replace('#','?test=1&release=1#'));await page.waitForFunction(()=>!!window.__counterpoint);state=await page.evaluate(()=>window.__counterpoint.state());assert.deepEqual(state.score,saved.score);for(let i=0;i<3;i++)assert.ok(Math.abs(state.camera[i]-saved.camera[i])<.0002);assert.equal(state.sound,false);
await page.reload();await page.waitForFunction(()=>!!window.__counterpoint);assert.deepEqual((await page.evaluate(()=>window.__counterpoint.state())).score,saved.score);
await page.locator('#reset').click();const w=await page.evaluate(()=>window.__counterpoint.targets().wheel);const before=await page.evaluate(()=>window.__counterpoint.state().time);await page.mouse.move(w.x,w.y);await page.mouse.down();await page.mouse.move(w.x-45,w.y-15,{steps:5});await page.mouse.up();assert.ok(Math.abs((await page.evaluate(()=>window.__counterpoint.state().time))-before)>.05);
await page.evaluate(()=>window.__counterpoint.setTime(21));await page.screenshot({path:`evidence/live-${run}-desktop.png`,timeout:120000});await page.setViewportSize({width:390,height:844});await page.screenshot({path:`evidence/live-${run}-mobile.png`,timeout:120000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const after=await page.evaluate(async()=>{const r=await fetch('./release.json',{cache:'no-store'});return r.json();});assert.deepEqual(after,metadata);assert.deepEqual(errors,[]);assert.deepEqual(badResponses,[]);
const report={pass:true,run,target,canonical,metadata,userAgent:await page.evaluate(()=>navigator.userAgent),errors,badResponses,stats:await page.evaluate(()=>window.__counterpoint.stats()),checks:['200 response and actual redirect','release metadata before and after','silent reduced-motion first frame','play/pause','keyboard time seek','note edit','audio user gesture','camera keys/reset','shared score and camera','refresh','flywheel reverse','desktop and 390px capture','console/network']};await mkdir('evidence',{recursive:true});await writeFile(`evidence/live-${run}.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report));await context.close();}finally{await browser.close();}
