import {chromium} from '@playwright/test';import {writeFile,mkdir} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import assert from 'node:assert/strict';
await mkdir('evidence/final-visual',{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const errors=[];const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(120000);
try{
await page.goto('http://localhost:5174/?test=1&t=21&quality=high');await page.waitForFunction(()=>!!window.__counterpoint);
const report={revision:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),userAgent:await page.evaluate(()=>navigator.userAgent),errors};
for(const [name,c] of [['selected',[.675,.95,13.5]],['front',[.05,1.05,13.5]],['rear',[2.6,1.0,14]]]){await page.evaluate(c=>window.__counterpoint.setCamera(c),c);await page.screenshot({path:'evidence/final-visual/'+name+'.png',timeout:120000});console.log('Captured',name);}
await page.evaluate(()=>window.__counterpoint.setCamera([.675,.95,13.5]));
const still=await page.evaluate(()=>window.__counterpoint.image('image/jpeg'));await writeFile('public/still.jpg',Buffer.from(still.split(',')[1],'base64'));
for(const t of [7.49,7.51,13.49,13.51,20.7,20.95,21,21.12,21.6,25.49,25.51,47.99,48,48.01]){await page.evaluate(t=>window.__counterpoint.setTime(t),t);const png=await page.evaluate(()=>window.__counterpoint.image('image/png'));await writeFile('evidence/final-visual/time-'+t+'.png',Buffer.from(png.split(',')[1],'base64'));}
async function measure(milliseconds){return page.evaluate(async duration=>{const intervals=[];let previous=performance.now();const start=previous;await new Promise(resolve=>{function frame(now){intervals.push(now-previous);previous=now;if(now-start>=duration)resolve();else requestAnimationFrame(frame);}requestAnimationFrame(frame);});const sorted=[...intervals].sort((a,b)=>a-b);return {durationMs:previous-start,samples:intervals.length,meanMs:intervals.reduce((a,b)=>a+b,0)/intervals.length,p95Ms:sorted[Math.floor(sorted.length*.95)],maximumMs:sorted.at(-1)};},milliseconds);}
const cdp=await context.newCDPSession(page);await cdp.send('HeapProfiler.collectGarbage');report.heapBefore=(await cdp.send('Runtime.getHeapUsage')).usedSize;
await page.evaluate(()=>window.__counterpoint.play());report.highTiming=await measure(6000);await page.evaluate(()=>window.__counterpoint.pause());report.high=await page.evaluate(()=>window.__counterpoint.stats());
await page.evaluate(()=>{window.__counterpoint.setQuality('low');window.__counterpoint.play();});report.lowTiming=await measure(8000);await page.evaluate(()=>window.__counterpoint.pause());report.low=await page.evaluate(()=>window.__counterpoint.stats());
await cdp.send('HeapProfiler.collectGarbage');report.heapAfter=(await cdp.send('Runtime.getHeapUsage')).usedSize;
await page.evaluate(()=>window.__counterpoint.play());const other=await context.newPage();await other.goto('about:blank');await other.bringToFront();report.nativeHidden=await page.evaluate(()=>({hidden:document.hidden,state:window.__counterpoint.state()}));await other.close();await page.bringToFront();
// Exercise the actual lifecycle handler where a headless engine does not hide tabs.
if(!report.nativeHidden.hidden){await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});report.simulatedHidden=await page.evaluate(()=>window.__counterpoint.state());await page.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});}
report.restored=await page.evaluate(()=>window.__counterpoint.state());assert.equal(report.restored.playing,false);
// Real captured mouse gesture: leaving the canvas must still end scrubbing.
await page.evaluate(()=>window.__counterpoint.setTime(21));const wheel=await page.evaluate(()=>window.__counterpoint.targets().wheel);await page.mouse.move(wheel.x,wheel.y);await page.mouse.down();await page.mouse.move(-20,-20,{steps:4});await page.mouse.up();report.outsideRelease=await page.evaluate(()=>window.__counterpoint.state());assert.equal(report.outsideRelease.scrubbing,false);
await page.locator('#reset').click();const wheel2=await page.evaluate(()=>window.__counterpoint.targets().wheel);await page.mouse.move(wheel2.x,wheel2.y);await page.mouse.down();await page.keyboard.press('Escape');await page.mouse.up();report.escapeCancel=await page.evaluate(()=>window.__counterpoint.state());assert.equal(report.escapeCancel.scrubbing,false);assert.equal(report.escapeCancel.playing,false);
const wav=await page.evaluate(async()=>{const a=await window.__counterpoint.offlineAudio(48);const bytes=new ArrayBuffer(44+a.length*2);const d=new DataView(bytes);const str=(at,s)=>{for(let i=0;i<s.length;i++)d.setUint8(at+i,s.charCodeAt(i));};str(0,'RIFF');d.setUint32(4,36+a.length*2,true);str(8,'WAVE');str(12,'fmt ');d.setUint32(16,16,true);d.setUint16(20,1,true);d.setUint16(22,1,true);d.setUint32(24,44100,true);d.setUint32(28,88200,true);d.setUint16(32,2,true);d.setUint16(34,16,true);str(36,'data');d.setUint32(40,a.length*2,true);for(let i=0;i<a.length;i++)d.setInt16(44+i*2,Math.max(-32768,Math.min(32767,Math.round(a[i]*32767))),true);let text='';const arr=new Uint8Array(bytes);for(let i=0;i<arr.length;i+=32768)text+=String.fromCharCode(...arr.subarray(i,i+32768));return btoa(text);});await writeFile('evidence/composition.wav',Buffer.from(wav,'base64'));
await writeFile('evidence/visual-performance.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));
await context.close();
const videoContext=await browser.newContext({viewport:{width:960,height:720},recordVideo:{dir:'evidence/recordings',size:{width:960,height:720}}});const vp=await videoContext.newPage();await vp.goto('http://localhost:5174/?test=1&quality=low');await vp.waitForFunction(()=>!!window.__counterpoint);await vp.waitForTimeout(25000);const w=await vp.evaluate(()=>window.__counterpoint.targets().wheel);await vp.mouse.move(w.x,w.y);await vp.mouse.down();await vp.mouse.move(w.x-80,w.y-30,{steps:30});await vp.mouse.up();await vp.evaluate(()=>window.__counterpoint.pause());await vp.mouse.move(80,250);await vp.mouse.down();await vp.mouse.move(220,280,{steps:25});await vp.mouse.up();await vp.waitForTimeout(1500);await vp.locator('#reset').click();await vp.locator('#play').click();await vp.waitForTimeout(5000);const video=vp.video();await videoContext.close();await video.saveAs('public/counterpoint.webm');console.log('Saved live browser recording');
}finally{await browser.close();}
